services:
  event-service:
    image: ghcr.io/cu2mber/event-service:latest
    container_name: event-service
    ports:
      - "8085:8085"
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    networks:
      - cu2mber-net
networks:
  cu2mber-net:
    external: true